version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/inventoryapp
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: AirQoHardWare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ss1234
    ports:
      - "5432:5432"
