name: app
description: AirQo mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# android test
version: 2.0.13+20025

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.3
  json_annotation: ^4.7.0
  http: ^0.13.5
  cached_network_image: ^3.2.3
  geolocator: ^9.0.2
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.11
  animations: ^2.0.7
  provider: ^6.0.5
  charts_flutter: ^0.12.0 # TODO: Use another package. charts_flutter is discontinued. https://pub.dev/packages/charts_flutter
  intl: ^0.17.0
  uuid: ^3.0.7
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  country_list_pick: ^1.0.1+6
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  in_app_review: ^2.0.6
  sentry_flutter: ^6.18.1
  lottie: ^2.1.0
  share_plus: ^6.3.0
  flutter_secure_storage: ^7.0.1
  geocoding: ^2.0.5
  flutter_dotenv: ^5.0.2
  auto_size_text: ^3.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.4
  firebase_analytics: ^10.1.0
  firebase_storage: ^11.0.10
  scrollable_positioned_list: ^0.3.5
  visibility_detector: ^0.3.3
  package_info_plus: ^3.0.2
  webview_flutter: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_in_app_messaging: ^0.7.0+10
  permission_handler: ^10.2.0
  firebase_crashlytics: ^3.0.9
  workmanager: ^0.5.1
  flutter_cache_manager: ^3.3.0
  path: ^1.8.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.12
  appinio_swiper: ^1.1.1
  # https://pub.dev/packages/retry
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  dart_code_metrics: ^5.3.0
  hive_generator: ^2.0.0
  drift_dev: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lottie/
    - .env.dev
    - .env.prod
