replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-reports
  tag: stage-881acf30-1730309646
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 31112
  targetPort: 3000
  port: 3000
ingress:
  enabled: false
nodeSelector: {}
torelations: {}
resources:
  requests:
    cpu: 10m
    memory: 150Mi
  limits:
    cpu: 50m
    memory: 200Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 80
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - moderate-usage
app:
  name: airqo-stage-reports
  label: airqo-reports
  namespace: staging
  configmap: env-reports-staging
