replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-reports
  tag: prod-e0fd1d3a-1720883137
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 30112
  targetPort: 3000
  port: 3000
ingress:
  enabled: false
nodeSelector: {}
torelations: {}
resources:
  requests:
    cpu: 5m
    memory: 60Mi
  limits:
    cpu: 100m
    memory: 150Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetMemoryUtilizationPercentage: 70
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
app:
  name: airqo-reports
  label: airqo-reports
  namespace: production
  configmap: env-reports-production
