apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-platform-resource
  namespace: production
spec:
  rules:
    - host: platform.airqo.net
      http:
        paths:
          - path: /calibrate
            pathType: Prefix
            backend:
              service:
                name: airqo-calibrate-app-svc
                port: 
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airqo-platform-svc
                port: 
                  number: 80
