###########################################################
# Start deployment of netmanager frontend - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-platform-frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: airqo-platform
  replicas: 4
  template:
    metadata:
      labels:
        app: airqo-platform
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: airqo-platform
          image: eu.gcr.io/airqo-250220/airqo-platform-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: airqo-platform
          envFrom:
            - configMapRef:
                name: env-platform-production
          resources:
            requests:
              # Average usage was 0.00001 vCPU and 60Mi over the last 30 days
              cpu: 5m
              memory: 60Mi
            limits:
              cpu: 100m
              memory: 150Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-platform-svc
  namespace: production
spec:
  selector:
    app: airqo-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-platform-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-platform-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
