replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-platform-frontend
  tag: stage-067cca88-1733864854
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 31101
  targetPort: 80
  port: 80
ingress:
  enabled: false
nodeSelector: {}
torelations: {}
resources:
  requests:
    cpu: 1m
    memory: 20Mi
  limits:
    cpu: 10m
    memory: 80Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 80
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - control-plane
app:
  name: airqo-stage-platform-frontend
  label: airqo-platform
  namespace: staging
  configmap: env-platform-staging
