version: '2'

services:              
  web-app:
    container_name: airqo-website
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: development
      args:
        REACT_WEB_STATIC_HOST: ${REACT_WEB_STATIC_HOST}
        REACT_NETMANAGER_BASE_URL: ${REACT_NETMANAGER_BASE_URL}
        REACT_APP_BASE_AIRQLOUDS_URL: ${REACT_APP_BASE_AIRQLOUDS_URL}
        REACT_APP_BASE_NEWSLETTER_URL: ${REACT_APP_BASE_NEWSLETTER_URL}
    entrypoint: /app/wsgi-entrypoint.sh    
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - dbHost

  dbHost:
    container_name: airqo-website-db
    restart: unless-stopped
    image: postgres:14.2-alpine
    environment:
      # This values are used in the backend settings file
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

