###########################################################
# Start deployment of calibrate app - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-calibrate-app
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-calibrate-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sta-calibrate-app
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - high-memory
      containers:
        - name: sta-calibrate-app
          image: eu.gcr.io/airqo-250220/airqo-stage-calibrate-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: sta-calibrate
          resources:
            requests:
              # Average usage was 0.0001 vCPU and 20Mi over the last 30 days
              cpu: 5m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 80Mi
          envFrom:
            - configMapRef:
                name: env-calibrate-staging

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-calibrate-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-calibrate-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-calibrate-app-svc
  namespace: staging
spec:
  selector:
    app: sta-calibrate-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31106
  type: NodePort
