replicaCount: 1
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-calibrate-app
  pullPolicy: Always
  tag: stage-c13a6217-1733912953
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: false
service:
  type: NodePort
  protocol: TCP
  port: 80
  targetPort: 80
  nodePort: 31106
resources:
  limits:
    cpu: 10m
    memory: 100Mi
  requests:
    cpu: 1m
    memory: 20Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 80
nodeSelector: 
  role: control-plane
tolerations: []
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - control-plane
        weight: 1
app:
  name: airqo-stage-calibrate-app
  label: sta-calibrate-app
  namespace: staging
  configmap: env-calibrate-staging
