###########################################################
# Start deployment of docs - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-docs
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: sta-docs
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: sta-docs
          image: us.gcr.io/airqo-250220/airqo-stage-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: docs
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 100Mi
