###########################################################
# Start deployment of docs - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-docs
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: sta-docs
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - general-purpose
      containers:
        - name: sta-docs
          image: us.gcr.io/airqo-250220/airqo-stage-docs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: docs
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 100Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-docs-svc
  namespace: staging
spec:
  selector:
    app: sta-docs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31104
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-docs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-docs
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
