###########################################################
# Start deployment of website - production
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-website
  namespace: production
spec:
  selector:
    matchLabels:
      app: airqo-website
  replicas: 4
  template:
    metadata:
      labels:
        app: airqo-website
    spec:
      containers:
        - name: airqo-website
          image: us.gcr.io/airqo-250220/airqo-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: airqo-website
          envFrom:
            - configMapRef:
                name: prod-website-config
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          resources: 
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 700Mi
          command: ["/app/wsgi-entrypoint.sh"]
      volumes:
        - name: config-volume
          configMap:
            name:  prod-website-config-files

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-website-svc
  namespace: production
spec:
  selector:
    app: airqo-website
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30105
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-website-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-website
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70