###########################################################
# Start deployment of netmanager frontend - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-platform-frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: airqo-platform
  replicas: 4
  template:
    metadata:
      labels:
        app: airqo-platform
    spec:
      containers:
        - name: airqo-platform
          image: us.gcr.io/airqo-250220/airqo-platform-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: airqo-platform
          envFrom:
            - configMapRef:
                name: env-platform-production
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 700Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-platform-svc
  namespace: production
spec:
  selector:
    app: airqo-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-platform-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-platform-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70