###########################################################
# Start deployment of platform frontend - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-platform-frontend
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-platform-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: sta-platform-ui
    spec:
      containers:
        - name: sta-platform-ui
          image: us.gcr.io/airqo-250220/airqo-stage-platform-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: sta-platform-ui
          envFrom:
            - configMapRef:
                name: env-platform-staging
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 700Mi

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-platform-ui-svc
  namespace: staging
spec:
  selector:
    app: sta-platform-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31104
  type: NodePort

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: airqo-stage-platform-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airqo-stage-platform-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80