replicaCount: 1
image:
  repository: eu.gcr.io/airqo-250220/airqo-stage-next-platform
  pullPolicy: Always
  tag: stage-33049363-1737029974
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 3000
  protocol: TCP
  targetPort: 3000
  nodePort: 31107
ingress:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 350Mi
  requests:
    cpu: 20m
    memory: 150Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: In
                values:
                  - control-plane
app:
  name: airqo-stage-next-platform
  label: sta-next-platform
  namespace: staging
  configmap: env-next-platform-staging
