replicaCount: 2
image:
  repository: eu.gcr.io/airqo-250220/airqo-inventory
  tag: prod-f834e7b6-1707411719
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
service:
  type: NodePort
  nodePort: 30108
  targetPort: 8000
  port: 8000
ingress:
  enabled: false
nodeSelector: {}
torelations: {}
resources:
  requests:
    cpu: 5m
    memory: 60Mi
  limits:
    cpu: 100m
    memory: 150Mi
autoscaling:
  minReplicas: 1
  maxReplicas: 4
  targetMemoryUtilizationPercentage: 70
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - general-purpose
      - weight: 1
        preference:
          matchExpressions:
            - key: node-type
              operator: In
              values:
                - high-memory
app:
  name: airqo-inventory
  label: airqo-inventory
  namespace: production
  configmap: env-inventory-production
