name: Flutter tests coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    name: Test codeCov
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.1.0
      with:
        credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v1.1.0

    - name: Add .env files
      run: |
        gcloud secrets versions access latest --secret="prod-env-mobile-app" > .env.prod
        gcloud secrets versions access latest --secret="prod-env-mobile-app" > .env.dev      

    - name: Install Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
          channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
        
    - name: Run tests
      run: flutter test --coverage
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        directory: mobile/coverage/