name: remove-deploy-previews

on:
  pull_request:
    branches: 
      - staging
    types:
      - closed

jobs:
  branch-name:
    name: Format branch name string
    runs-on: ubuntu-latest
    outputs:
      lowercase: ${{ steps.string.outputs.lowercase }} # lowercase version
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.head_ref || github.ref_name }}

  check:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: check for available deploy previews
    outputs:
      remove_platform_preview: ${{ steps.check_files.outputs.remove_platform_preview }} # remove platform preview
      remove_calibrate_app_preview: ${{ steps.check_files.outputs.remove_calibrate_app_preview }} # remove calibrate app preview

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified frontends
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          echo "::set-output name=remove_platform_preview::false"  
          echo "::set-output name=remove_calibrate_app_preview::false"  

          while IFS= read -r file
          do
            echo $file
            if [[ $file == netmanager/* ]]; then
              echo "::set-output name=remove_platform_preview::true"
            fi

            if [[ $file == calibrate/* ]]; then
              echo "::set-output name=remove_calibrate_app_preview::true"  
            fi

          done < files.txt

  ### remove platform deploy preview ###
  remove-platform-preview:
    name: remove-platform-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_platform_preview == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS }}'
          
      - name: Setup Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-platform-preview \
            --region=${{ secrets.REGION }} \
            --quiet

  ### remove calibrate-app deploy preview ###
  remove-calibrate-app-preview:
    name: remove-calibrate-app-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_calibrate_app_preview == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS }}'
          
      - name: Setup Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-calibrate-app-preview \
            --region=${{ secrets.REGION }} \
            --quiet