runtime: php74
env: standard
service: default

handlers:
  - url: /(.+\.(assets|js|css|gif|png|jpeg|jpg|svg|ico|bmp|ttf|woff|eot|mp4|mp3|pdf|webp))$
    static_files: \1
    upload: .+\.(assets|js|css|gif|png|jpeg|jpg|svg|ico|bmp|ttf|woff|eot|mp4|mp3|pdf|webp)$

  - url: /apis/(.+)\.php
    script: auto

  - url: /dsa/
    static_files: dsa/index.html
    upload: dsa/index.html

  - url: /docs/
    static_files: docs/Privacy-Policy-For-AirQo.pdf
    upload: docs/Privacy-Policy-For-AirQo.pdf

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301